spring.application.name=base_team

server.port=8081
# Configuracion para la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/team
spring.datasource.username=postgres
spring.datasource.password=cisco123
spring.datasource.driver-class-name=org.postgresql.Driver
